### ISSUE TITLE
HTTP URL和Response架构调整

### ISSUE THREAD

**Issue by winlinvip** [winlinvip/simple-rtmp-server#277]
参考GO的http模块，调整SRS的HTTP模块架构。

**Comment by winlinvip** [comment]
go的api匹配：
```
(gdb) bt
#0  main.func·001 (w=..., req=0xc208034340) at /home/winlin/bravo-uploader/src/upload.go:274
#1  0x0000000000482031 in net/http.HandlerFunc.ServeHTTP (f={void (net/http.ResponseWriter, struct net/http.Request *)} 0xc20802fc58, w=..., 
    r=0xc208034340) at /usr/local/go/src/net/http/server.go:1265
#2  0x000000000048379d in net/http.(*ServeMux).ServeHTTP (mux=0xc20800a6f0, w=..., r=0xc208034340)
    at /usr/local/go/src/net/http/server.go:1541
#3  0x000000000048416a in net/http.serverHandler.ServeHTTP (sh=..., rw=..., req=0xc208034340) at /usr/local/go/src/net/http/server.go:1703
#4  0x0000000000481b87 in net/http.(*conn).serve (c=0xc2080443c0) at /usr/local/go/src/net/http/server.go:1204
#5  0x0000000000440cf1 in runtime.goexit () at /usr/local/go/src/runtime/asm_amd64.s:2232
#6  0x000000c2080443c0 in ?? ()
#7  0x0000000000000000 in ?? ()
```

静态文件的匹配：
```
#0  net/http.(*fileHandler).ServeHTTP (f=0xc20802a860, w=..., r=0xc208034340) at /usr/local/go/src/net/http/fs.go:446
#1  0x000000000048379d in net/http.(*ServeMux).ServeHTTP (mux=0xc20800a6f0, w=..., r=0xc208034340)
    at /usr/local/go/src/net/http/server.go:1541
#2  0x000000000048416a in net/http.serverHandler.ServeHTTP (sh=..., rw=..., req=0xc208034340) at /usr/local/go/src/net/http/server.go:1703
#3  0x0000000000481b87 in net/http.(*conn).serve (c=0xc2080443c0) at /usr/local/go/src/net/http/server.go:1204
#4  0x0000000000440cf1 in runtime.goexit () at /usr/local/go/src/runtime/asm_amd64.s:2232
```

**Comment by winlinvip** [comment]
go使用了匹配：
```
// ServeHTTP dispatches the request to the handler whose
// pattern most closely matches the request URL.
func (mux *ServeMux) ServeHTTP(w ResponseWriter, r *Request) {
	if r.RequestURI == "*" {
		if r.ProtoAtLeast(1, 1) {
			w.Header().Set("Connection", "close")
		}
		w.WriteHeader(StatusBadRequest)
		return
	}
	h, _ := mux.Handler(r)
	h.ServeHTTP(w, r)
}
```

在Handler中找出匹配的handler：
```

// Handle registers the handler for the given pattern.
// If a handler already exists for pattern, Handle panics.
func (mux *ServeMux) Handle(pattern string, handler Handler) {
	mux.mu.Lock()
	defer mux.mu.Unlock()

	if pattern == "" {
		panic("http: invalid pattern " + pattern)
	}
	if handler == nil {
		panic("http: nil handler")
	}
	if mux.m[pattern].explicit {
		panic("http: multiple registrations for " + pattern)
	}

	mux.m[pattern] = muxEntry{explicit: true, h: handler, pattern: pattern}

	if pattern[0] != '/' {
		mux.hosts = true
	}

	// Helpful behavior:
	// If pattern is /tree/, insert an implicit permanent redirect for /tree.
	// It can be overridden by an explicit registration.
	n := len(pattern)
	if n > 0 && pattern[n-1] == '/' && !mux.m[pattern[0:n-1]].explicit {
		// If pattern contains a host name, strip it and use remaining
		// path for redirect.
		path := pattern
		if pattern[0] != '/' {
			// In pattern, at least the last character is a '/', so
			// strings.Index can't be -1.
			path = pattern[strings.Index(pattern, "/"):]
		}
		mux.m[pattern[0:n-1]] = muxEntry{h: RedirectHandler(path, StatusMovedPermanently), pattern: pattern}
	}
}
```

**Comment by winlinvip** [comment]
查找handler：
```

// Handler returns the handler to use for the given request,
// consulting r.Method, r.Host, and r.URL.Path. It always returns
// a non-nil handler. If the path is not in its canonical form, the
// handler will be an internally-generated handler that redirects
// to the canonical path.
//
// Handler also returns the registered pattern that matches the
// request or, in the case of internally-generated redirects,
// the pattern that will match after following the redirect.
//
// If there is no registered handler that applies to the request,
// Handler returns a ``page not found'' handler and an empty pattern.
func (mux *ServeMux) Handler(r *Request) (h Handler, pattern string) {
	if r.Method != "CONNECT" {
		if p := cleanPath(r.URL.Path); p != r.URL.Path {
			_, pattern = mux.handler(r.Host, p)
			url := *r.URL
			url.Path = p
			return RedirectHandler(url.String(), StatusMovedPermanently), pattern
		}
	}

	return mux.handler(r.Host, r.URL.Path)
}
```

**Comment by winlinvip** [comment]
处理request时调用这个默认handler：
```
func (sh serverHandler) ServeHTTP(rw ResponseWriter, req *Request) {
	handler := sh.srv.Handler
	if handler == nil {
		handler = DefaultServeMux
	}
	if req.RequestURI == "*" && req.Method == "OPTIONS" {
		handler = globalOptionsHandler{}
	}
	handler.ServeHTTP(rw, req)
}
```

**Comment by winlinvip** [comment]
go的匹配规则：
```// Does path match pattern?
func pathMatch(pattern, path string) bool {
	if len(pattern) == 0 {
		// should not happen
		return false
	}
	n := len(pattern)
	if pattern[n-1] != '/' {
		return pattern == path
	}
	return len(path) >= n && path[0:n] == pattern
}
```
如果不是以/结尾，那么就精确匹配。
否则就只匹配前面的一部分，这样/就能匹配所有路径，/api/能匹配/api/[xxxx]。

**Comment by winlinvip** [comment]
go写入数据的函数是：
```
// either dataB or dataS is non-zero.
func (w *response) write(lenData int, dataB []byte, dataS string) (n int, err error) {
```

**Comment by wuxianlijiang** [comment]
辛苦了。
